# Audit Logging Configuration — FedRAMP AU-2, AU-3
# Deploy audit policy to API server configuration

---
# Kubernetes Audit Policy
# Place at /etc/kubernetes/audit-policy.yaml on control plane
apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  name: fedramp-audit-policy
rules:
  # Don't log requests to health endpoints
  - level: None
    nonResourceURLs:
      - /healthz*
      - /readyz*
      - /livez*

  # Don't log watch requests (too noisy)
  - level: None
    verbs: ["watch", "list"]

  # Log secret operations at Metadata level (don't log secret values)
  - level: Metadata
    resources:
      - group: ""
        resources: ["secrets"]
    omitStages:
      - RequestReceived

  # Log RBAC changes at RequestResponse level
  - level: RequestResponse
    resources:
      - group: "rbac.authorization.k8s.io"
        resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]

  # Log pod exec/attach at Request level
  - level: Request
    resources:
      - group: ""
        resources: ["pods/exec", "pods/attach", "pods/portforward"]

  # Log namespace operations
  - level: RequestResponse
    resources:
      - group: ""
        resources: ["namespaces"]

  # Log service account operations
  - level: Metadata
    resources:
      - group: ""
        resources: ["serviceaccounts"]

  # Log all other write operations at Request level
  - level: Request
    verbs: ["create", "update", "patch", "delete"]

  # Log everything else at Metadata level
  - level: Metadata

---
# Falco rules for audit monitoring (deploy via Helm values)
# Detects suspicious kubectl exec, secret access, RBAC changes
apiVersion: v1
kind: ConfigMap
metadata:
  name: fedramp-falco-rules
  namespace: fedramp-demo
  labels:
    fedramp-control: AU-2
data:
  fedramp-rules.yaml: |
    - rule: FedRAMP - Unauthorized Secret Access
      desc: Detect access to Kubernetes secrets outside normal operations
      condition: >
        ka.verb in (get, list) and
        ka.target.resource = secrets and
        not ka.user.name in (system:kube-controller-manager, system:kube-scheduler)
      output: >
        FedRAMP AU-2: Secret accessed (user=%ka.user.name resource=%ka.target.name
        namespace=%ka.target.namespace verb=%ka.verb)
      priority: WARNING
      tags: [fedramp, AU-2, secrets]

    - rule: FedRAMP - kubectl exec into Pod
      desc: Detect interactive exec sessions into pods
      condition: >
        ka.verb = create and
        ka.target.subresource = exec
      output: >
        FedRAMP AU-2: kubectl exec detected (user=%ka.user.name
        pod=%ka.target.name namespace=%ka.target.namespace)
      priority: NOTICE
      tags: [fedramp, AU-2, exec]

    - rule: FedRAMP - RBAC Modification
      desc: Detect changes to RBAC resources
      condition: >
        ka.verb in (create, update, patch, delete) and
        ka.target.resource in (roles, rolebindings, clusterroles, clusterrolebindings)
      output: >
        FedRAMP AU-2: RBAC modified (user=%ka.user.name verb=%ka.verb
        resource=%ka.target.resource name=%ka.target.name)
      priority: WARNING
      tags: [fedramp, AU-2, AC-2, rbac]
