# RBAC Templates — FedRAMP AC-2, AC-3
# Minimal RBAC for DVWA application deployment

---
# Dedicated ServiceAccount (don't use default)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dvwa-sa
  namespace: fedramp-demo
  labels:
    app: dvwa
    fedramp-control: AC-2
automountServiceAccountToken: false

---
# Read-only role for application monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dvwa-readonly
  namespace: fedramp-demo
  labels:
    fedramp-control: AC-3
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
# Application deployer role (no secrets access)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dvwa-deployer
  namespace: fedramp-demo
  labels:
    fedramp-control: AC-3
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  # Explicitly NO access to secrets

---
# Bind deployer role to CI service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dvwa-deployer-binding
  namespace: fedramp-demo
  labels:
    fedramp-control: AC-2
subjects:
  - kind: ServiceAccount
    name: dvwa-sa
    namespace: fedramp-demo
roleRef:
  kind: Role
  name: dvwa-deployer
  apiGroup: rbac.authorization.k8s.io

---
# Security auditor — read-only cluster-wide for compliance checks
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fedramp-auditor
  labels:
    fedramp-control: AC-2
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "configmaps", "serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["get", "list"]
