apiVersion: v1
kind: Service
metadata:
  name: anthra-db
  namespace: anthra
  labels:
    app: anthra-db
    owner: anthra-team
    cost-center: anthra-saas
    data-classification: confidential
  annotations:
    logging.ghostprotocol.io/audit-enabled: "true"
spec:
  type: ClusterIP
  selector:
    app: anthra-db
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: 5432
