apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fedramp-require-drop-all-capabilities
  annotations:
    policies.kyverno.io/title: Require Drop All Capabilities
    policies.kyverno.io/category: FedRAMP AC-6
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      FedRAMP AC-6 (Least Privilege): Containers must drop ALL Linux
      capabilities. Specific capabilities can be added back explicitly.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          FedRAMP AC-6: All containers must drop ALL capabilities.
          Add spec.containers[*].securityContext.capabilities.drop: ["ALL"]
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: ALL
                    operator: AnyNotIn
                    value: "{{ element.securityContext.capabilities.drop || `[]` }}"
